### ISSUE TITLE
Denon Test fails.

### ISSUE THREAD

**Issue by DarkCinema** [lmoe/node-denon-client#1]
When running the denon_test.js I receive the volume and max volume info then I get nothing.
No input & surround information. Any idea why?
I am using a Marantz NR1604.

**Comment by DarkCinema** [comment]
Solved: 
Added input options:

const InputOptions = {
    CD: 'CD',
    Tuner: 'TUNER',
    DVD: 'DVD',
    BD: 'BD',
    TV: 'TV',
    Sattelite: 'SAT/CBL',
    Cable: 'SAT/CBL',
    MediaPlayer: 'SMPLAY',
    Game: 'GAME',
    Aux1: 'AUX1',
    Aux2: 'AUX2',
    MPLAY: 'MPLAY',
    MXPORT: 'M-XPORT',
    GAME: 'GAME',
    Net: 'NET',
    IPod: 'USB/IPOD',
    USB: 'USB',    
    Status: '?',
    Base: 'SI'
};

**Comment by lmoe** [comment]
Thank you, I had forgot about this issue. I have added the new options to the list :)
